// Generated by CoffeeScript 1.6.2
// https://github.com/geta6/libime.js

var LibIME;

LibIME = (function() {
  var _directinput, _element, _except_keys, _num_press, _num_up;

  _element = null;

  _directinput = false;

  _num_up = 0;

  _num_press = 0;

  _except_keys = [8, 16, 17, 18, 91];

  LibIME.prototype.onkeydown = function() {
    return true;
  };

  LibIME.prototype.onkeypress = function() {
    return true;
  };

  LibIME.prototype.onkeyup = function() {
    return true;
  };

  LibIME.prototype.status = 0;

  LibIME.prototype.parse = function(status) {
    if (status === 2) {
      return '直接入力中';
    }
    if (status === 1) {
      return 'IME確定';
    }
    if (status === 0) {
      return 'IME入力中';
    }
  };

  function LibIME(expr) {
    var eventer,
      _this = this;

    if (typeof expr !== 'string') {
      _element = expr;
    } else {
      if (typeof jQuery !== "undefined" && jQuery !== null) {
        _element = $(expr);
      } else if (document.querySelector != null) {
        _element = document.querySelector(expr);
      } else {
        throw new Error('expr isnt object');
      }
    }
    eventer = 'addEventListener';
    if (typeof jQuery !== "undefined" && jQuery !== null) {
      eventer = 'on';
    }
    if (_element[eventer] == null) {
      throw new Error('invalid object or expr passed, must be jQuery/Raw DOM object');
    }
    _element[eventer]('keydown', function(event) {
      _directinput = false;
      _num_press = 0;
      _num_up = 0;
      return _this.onkeydown(arguments);
    });
    _element[eventer]('keypress', function(event) {
      _directinput = true;
      _num_press += 1;
      return _this.onkeypress(arguments);
    });
    _element[eventer]('keyup', function(event) {
      _num_up += 1;
      if ((_except_keys.indexOf(event.keyCode)) === -1) {
        if (!_directinput && event.keyCode === 13) {
          _this.status = 1;
        } else if (!_directinput && _num_press === 0) {
          _this.status = 0;
        } else {
          _this.status = 2;
        }
      } else {
        _this.status = 2;
      }
      return _this.onkeyup(arguments);
    });
  }

  return LibIME;

})();
